import logging

# Biolink Entities
BIOLINK_GENE = 'biolink:Gene'
BIOLINK_DRUG = 'biolink:Drug'
BIOLINK_DISEASE = 'biolink:Disease'
BIOLINK_PHENOTYPIC_FEATURE = 'biolink:PhenotypicFeature'

# Edge Property Constants
BIOLINK_CONTRIBUTION = 'biolink:has_evidence'
BIOLINK_PROBABILITY = 'biolink:has_confidence_level'

# Biolink Predicate/Association/Slot Constants
BIOLINK_GENE_TO_DISEASE_PREDICATE = 'biolink:gene_associated_with_condition'
BIOLINK_CHEMICAL_TO_DISEASE_OR_PHENOTYPIC_FEATURE_PREDICATE = 'biolink:treats'
BIOLINK_CHEMICAL_TO_GENE_PREDICATE = 'biolink:interacts_with'
BIOLINK_GENE_TO_CHEMICAL_PREDICATE = 'biolink:interacts_with'
BIOLINK_DISEASE_TO_PHENOTYPIC_FEATURE_PREDICATE = 'biolink:has_phenotype'

# Maps
SUBJECT_TO_OBJECT_PREDICATE_MAP = {
        (BIOLINK_GENE, BIOLINK_DRUG): BIOLINK_GENE_TO_CHEMICAL_PREDICATE,
        (BIOLINK_DRUG, BIOLINK_GENE): BIOLINK_CHEMICAL_TO_GENE_PREDICATE,
        (BIOLINK_GENE, BIOLINK_DISEASE): BIOLINK_GENE_TO_DISEASE_PREDICATE,
        (BIOLINK_DRUG, BIOLINK_DISEASE): BIOLINK_CHEMICAL_TO_DISEASE_OR_PHENOTYPIC_FEATURE_PREDICATE,
        }
