import logging

# Biolink Entities
BIOLINK_GENE = 'gene'
BIOLINK_DRUG = 'drug'
BIOLINK_DISEASE = 'disease'
BIOLINK_PHENOTYPIC_FEATURE = 'phenotypic feature'

# Edge Property Constants
BIOLINK_CONTRIBUTION = 'has evidence'
BIOLINK_PROBABILITY = 'has confidence level'

# Biolink Predicate/Association/Slot Constants
BIOLINK_GENE_TO_DISEASE_PREDICATE = 'gene associated with condition'
BIOLINK_CHEMICAL_TO_DISEASE_OR_PHENOTYPIC_FEATURE_PREDICATE = 'treats'
BIOLINK_CHEMICAL_TO_GENE_PREDICATE = 'interacts_with'
BIOLINK_GENE_TO_CHEMICAL_PREDICATE = 'interacts_with'
BIOLINK_DISEASE_TO_PHENOTYPIC_FEATURE_PREDICATE = 'has_phenotype'

# Maps
SUBJECT_TO_OBJECT_PREDICATE_MAP = {
        (BIOLINK_GENE, BIOLINK_DRUG): BIOLINK_GENE_TO_CHEMICAL_PREDICATE,
        (BIOLINK_DRUG, BIOLINK_GENE): BIOLINK_CHEMICAL_TO_GENE_PREDICATE,
        (BIOLINK_GENE, BIOLINK_DISEASE): BIOLINK_GENE_TO_DISEASE_PREDICATE,
        (BIOLINK_DRUG, BIOLINK_DISEASE): BIOLINK_CHEMICAL_TO_DISEASE_OR_PHENOTYPIC_FEATURE_PREDICATE,
        }
